version: '2'
services:
  php:
    image: yiisoftware/yii2-php:8.2-apache
    container_name: yii_jessica
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    ports:
      - '8000:80'
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: testsoft
    ports:
      - '3306:3306'
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080